# This is your vagrant environment config
---
vagrant:
    vm:
        base_box: ubuntu/xenial64               # Required
        base_box_osx: geerlingguy/ubuntu1604    # Optional
        base_box_win: someuser/anotherbox       # Optional
        box_user: ubuntu                        # Required
        hostname: awesome.dev                   # Required
        ip: 192.168.22.124                      # Required
        memory: '2048'                          # Required, measured in megabytes
        cpus: '2'                               # Required, number of CPU cores
    synced_folders:                             # At least one is required
        1: { source: ./, target: /var/www/awesome.dev }

server_timezone: Europe/London
server_locale: en_GB.UTF-8
server_packages:
    - zip
    - curl
    - unzip
server_ntp_servers:
    - 0.europe.pool.ntp.org
    - 1.europe.pool.ntp.org
    - 2.europe.pool.ntp.org
    - 3.europe.pool.ntp.org