---
- hosts: staging
  become: true
  vars:
      - env: staging
  roles:
      - { role: ansible/roles/vagrant }
      - { role: ansible/roles/php }
      - { role: ansible/roles/nginx }
      - { role: ansible/roles/database }
      - { role: ansible/roles/app }
